version: 0.0
os: linux
files:
  - source: target/cloud-comp-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/cloudauto

hooks:
  # Optional: Sie können hier auch Lifecycle-Hooks definieren, wie z.B. das Starten Ihrer Anwendung
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 180
